image: node:latest

stages:
  - test
  - qa
  - deploy

before_script:
  - npm install

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

test:lint:
  stage: test
  script:
    - npm run lint

test:karma:
  stage: test
  image: trion/ng-cli-karma
  allow_failure: false
  script:
    - npm run test-prod
  artifacts:
    paths:
      - coverage/

sonarcloud-check:
  stage: qa
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: ['']
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - node_modules/
      - .sonar/cache
  script:
    - sonar-scanner
  dependencies:
    - test:karma
  only:
    - master

deploy:
  stage: deploy
  image: trion/ng-cli
  script:
    - ng build ngx-error-message --prod
    - cd dist/ngx-error-message
    - echo '//registry.npmjs.org/:_authToken='${NPM_TOKEN}>.npmrc
    - npm publish
  only:
    - tags
